### ISSUE TITLE
Unable to import TS file from Svelte file

### ISSUE THREAD

**Issue by tomasbonco** [pyoner/svelte-typescript#15]
**Describe the bug**
The path of .ts dependency can't be resolved by .svelte file.

**To Reproduce**
1. Create a `store.ts` file, with content:
```ts
import { writable } from 'svelte/store'
export const something = writable( 10 )
```

2. In `App.svelte` add following line:
```ts
import {something} from './store'
```

And you'll get:
```bash
[!] Error: Could not resolve './store' from src\App.svelte
Error: Could not resolve './store' from src\App.svelte
    at error (d:\node\bug-repro\node_modules\rollup\dist\rollup.js:10162:30)
    at ModuleLoader.handleMissingImports (d:\node\bug-repro\node_modules\rollup\dist\rollup.js:17237:17)
    at ModuleLoader.<anonymous> (d:\node\bug-repro\node_modules\rollup\dist\rollup.js:17288:26)
    at Generator.next (<anonymous>)
    at fulfilled (d:\node\bug-repro\node_modules\rollup\dist\rollup.js:40:28)
    at <anonymous>
```

**Expected behavior**
Everything should be awesome, no errors reported.

**Additional context**
During filling of this bug I found out that `import {something} from './store.ts'` does work, but throws error into console:
```
src/App.svelte:4:27 - error TS2691: An import path cannot end with a '.ts' extension. Consider importing './store' instead.
```

**Comment by tomasbonco** [comment]
Even thou ignoring the error and using `import .. from './store.ts'` might look like a solution, there is an issue. Reference of `store.ts` imported in `main.ts` is different than the one imported inside `App.svelte` (each of them creates its own store). It makes the whole concept useless.

**Comment by pyoner** [comment]
@tomasbonco
The problem in **rollup-plugin-typescript2** https://github.com/ezolenko/rollup-plugin-typescript2/issues/172
To quick fix I recommend downgrading the rollup-plugin-typescript2 to version "0.21.0"
