### ISSUE TITLE
After updating from Svelte 3.20.1 npm run fails "Cannot find module 'typescript'"

### ISSUE THREAD

**Issue by crazedVic** [pyoner/svelte-typescript#30]
**Describe the bug**
I just was looking to run npm install and get my project updated.  I have not used Typescript and have no intention of using Typescript in the foreseeable future on this project.

**To Reproduce**
1. Open existing project folder, type npm update.
2. Installation completes.  Svelte now at version 3.28.0
3. Type npm run dev
```
[!] (plugin svelte) Error: [svelte-preprocess] Error transforming 'typescript'.

Message:
Cannot find module 'typescript'
Require stack:
- /node_modules/svelte-preprocess/dist/transformers/typescript.js
- /node_modules/svelte-preprocess/dist/modules/transformers.js
- /node_modules/svelte-preprocess/dist/autoProcess.js
- /node_modules/svelte-preprocess/dist/index.js
- /rollup.config.js
- /node_modules/rollup/dist/bin/rollup

Stack:
Error: Cannot find module 'typescript'
Require stack:
- /node_modules/svelte-preprocess/dist/transformers/typescript.js
- /node_modules/svelte-preprocess/dist/modules/transformers.js
- /node_modules/svelte-preprocess/dist/autoProcess.js
- /node_modules/svelte-preprocess/dist/index.js
- /rollup.config.js
- /node_modules/rollup/dist/bin/rollup
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/node_modules/svelte-preprocess/dist/transformers/typescript.js:1:281)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
node_modules/sveltestrap/src/Icon.svelte
Error: [svelte-preprocess] Error transforming 'typescript'.
```

**Expected behavior**
As I was not using Typescript before I would expect it not to become a requirement now.

**Files**
Config Files before update where project compiles and runs fine:
[Before update and works.zip](https://github.com/pyoner/svelte-typescript/files/5284505/Before.update.and.works.zip)

Config Files after update where project no longer runs:
[After_update.zip](https://github.com/pyoner/svelte-typescript/files/5284491/After_update.zip)

**Comment by crazedVic** [comment]
crap just realized not in the main github repo, sorry about that

**Comment by pyoner** [comment]
@crazedVic no problem :)
